string assignment
---
# sources
string[] sources

# predicates
string[] predicates

# reported length for this predicate
int32[] lengths

# possible other assignments for these predicates
string[] assignments
