geometry_msgs/Pose[] transforms
string[] names
string frame_type
predicator_msgs/PredicateStatement[] predicates
---
# returns the set of possible waypoints
geometry_msgs/PoseArray waypoints
string[] names
string msg
bool success
