predicator_msgs/PredicateStatement[] predicates # predicates to match when moving
geometry_msgs/Pose pose # offset to move to
string obj_class # class to move to
string name # name of the requested motion
float32 accel
float32 vel
float32 backoff # distance to move back when doing grasp or release
---
string ack # what happened
