#!/usr/bin/env python

import sys

from rqt_gui.main import Main
from instructor_core.builder import Builder

plugin = 'instructor'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))#, plugin_argument_provider=Dot.add_arguments))
